### ISSUE TITLE
Property Review System

### ISSUE THREAD

**Issue by surfdemon** [surfdemon/gainpace-property#5]
As an administrator, I want to review and manage property listings so that I can ensure quality content on the platform

**Comment by surfdemon** [comment]
**Acceptance Criteria:** 
- When a property is added, it should be added as a draft
- Ability to change the status of a property in the admin area

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Created a Property model in models.py and registered it in admin.py to allow administrators to review and manage property listings.

You can review changes in this commit: https://github.com/jjyutm4532/surfdemon-gainpace-property-5/commit/abeb91c94d8cefdc37a1a5ba287ada3494b9be33.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
